cameras:
  static:
    _target_: calvin_env.camera.static_camera.StaticCamera
    name: static
    fov: 10
    aspect: 1
    nearval: 0.01
    farval: 10
    width: 200
    height: 200
    look_at:
    - -0.026242351159453392
    - -0.0302329882979393
    - 0.3920000493526459
    look_from:
    - 2.871459009488717
    - -2.166602199425597
    - 2.555159848480571
    up_vector:
    - 0.4041403970338857
    - 0.22629790978217404
    - 0.8862616969685161
  gripper:
    _target_: calvin_env.camera.gripper_camera.GripperCamera
    name: gripper
    fov: 75
    aspect: 1
    nearval: 0.01
    farval: 2
    width: 84
    height: 84
  tactile:
    _target_: calvin_env.camera.tactile_sensor.TactileSensor
    name: tactile
    width: 120
    height: 160
    digit_link_ids:
    - 10
    - 12
    visualize_gui: false
    config_path: conf/digit_sensor/config_digit.yml
env:
  _target_: mdt.models.rl.env.PlayTableTaskEnv
  _recursive_: false
  task_annotation: ${annotation}
  language_embedding_path: /home/edward/projects/mdt_policy/dataset/calvin_debug_dataset/validation/lang_clip_resnet50/embeddings.npy
  num_sequences: 10
  task_cfg: ${tasks}
  cameras: ${cameras}
  seed: 0
  bullet_time_step: 240.0
  use_vr: false
  show_gui: ${show_gui}
  robot_cfg: ${robot}
  scene_cfg: ${scene}
  use_scene_info: true
  use_egl: true
  control_freq: 30
  observation_space_keys:
    rgb_obs:
    - rgb_static
    - rgb_gripper
    - rgb_tactile
    depth_obs: []
    state_obs:
    - robot_obs
    actions:
    - rel_actions
    language:
    - language

  transforms:
    residual:
      rgb_static:
      - _target_: torchvision.transforms.v2.Resize
        size: [224, 224]
        antialias: true
      - _target_: mdt.utils.transforms.RandomShiftsAug
        pad: 10
      - _target_: mdt.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.v2.Normalize
        mean:
        - 0.48145466
        - 0.4578275
        - 0.40821073
        std:
        - 0.26862954
        - 0.26130258
        - 0.27577711
      rgb_gripper:
      - _target_: torchvision.transforms.v2.Resize
        size: [84, 84]
        antialias: true
      - _target_: mdt.utils.transforms.RandomShiftsAug
        pad: 4
      - _target_: mdt.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.v2.Normalize
        mean:
        - 0.48145466
        - 0.4578275
        - 0.40821073
        std:
        - 0.26862954
        - 0.26130258
        - 0.27577711
      rgb_tactile:
      - _target_: torchvision.transforms.v2.Resize
        size: [120, 120]
        antialias: true
      - _target_: mdt.utils.transforms.RandomShiftsAug
        pad: 4
      - _target_: mdt.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.v2.Normalize
        mean:
        - 0.48145466
        - 0.4578275
        - 0.40821073
        std:
        - 0.26862954
        - 0.26130258
        - 0.27577711
      depth_static:
      - _target_: torchvision.transforms.v2.Resize
        size: [200, 200]
      - _target_: mdt.utils.transforms.AddDepthNoise
        shape:
        - 1000.0
        rate:
        - 1000.0
      - _target_: mdt.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      depth_gripper:
      - _target_: torchvision.transforms.v2.Resize
        size: [84, 84]
      - _target_: mdt.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      depth_tactile:
      - _target_: torchvision.transforms.v2.Resize
        size: [84, 84]
        antialias: true
      - _target_: mdt.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      robot_obs:
      - _target_: mdt.utils.transforms.NormalizeVector
      - _target_: mdt.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      scene_obs:
      - _target_: mdt.utils.transforms.NormalizeVector
      - _target_: mdt.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      language:
      - _target_: mdt.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
    mdt:
      rgb_static:
      - _target_: torchvision.transforms.v2.Resize
        size: [224, 224]
        antialias: true
      - _target_: mdt.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.v2.Normalize
        mean:
        - 0.48145466
        - 0.4578275
        - 0.40821073
        std:
        - 0.26862954
        - 0.26130258
        - 0.27577711
      rgb_gripper:
      - _target_: torchvision.transforms.v2.Resize
        size: [84, 84]
        antialias: true
      - _target_: mdt.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.v2.Normalize
        mean:
        - 0.48145466
        - 0.4578275
        - 0.40821073
        std:
        - 0.26862954
        - 0.26130258
        - 0.27577711
      depth_static:
      - _target_: torchvision.transforms.v2.Resize
        size: 200
      depth_gripper:
      - _target_: torchvision.transforms.v2.Resize
        size: 84
      rgb_tactile:
      - _target_: torchvision.transforms.v2.Resize
        size: [120, 120]
      - _target_: mdt.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.v2.Normalize
        mean:
        - 0.48145466
        - 0.4578275
        - 0.40821073
        std:
        - 0.26862954
        - 0.26130258
        - 0.27577711
      depth_tactile:
      - _target_: torchvision.transforms.v2.Resize
        size: 64
      - _target_: torchvision.transforms.v2.Normalize
        mean:
        - 0.1
        std:
        - 0.2
      robot_obs:
      - _target_: mdt.utils.transforms.NormalizeVector
      scene_obs:
      - _target_: mdt.utils.transforms.NormalizeVector
scene:
  _target_: calvin_env.scene.play_table_scene.PlayTableScene
  _recursive_: false
  data_path: ${data_path}
  global_scaling: 0.8
  euler_obs: ${robot.euler_obs}
  robot_base_position:
  - -0.34
  - -0.46
  - 0.24
  robot_base_orientation:
  - 0
  - 0
  - 0
  robot_initial_joint_positions:
  - -1.21779206
  - 1.03987646
  - 2.11978261
  - -2.34205014
  - -0.87015947
  - 1.64119353
  - 0.55344866
  surfaces:
    table:
    - - 0.0
      - -0.15
      - 0.46
    - - 0.35
      - -0.03
      - 0.46
    slider_left:
    - - -0.32
      - 0.05
      - 0.46
    - - -0.16
      - 0.12
      - 0.46
    slider_right:
    - - -0.05
      - 0.05
      - 0.46
    - - 0.13
      - 0.12
      - 0.46
  objects:
    fixed_objects:
      table:
        file: calvin_table_D/urdf/calvin_table_D.urdf
        initial_pos:
        - 0
        - 0
        - 0
        initial_orn:
        - 0
        - 0
        - 0
        joints:
          base__slide:
            initial_state: 0
          base__drawer:
            initial_state: 0
        buttons:
          base__button:
            initial_state: 0
            effect: led
        switches:
          base__switch:
            initial_state: 0
            effect: lightbulb
        lights:
          lightbulb:
            link: light_link
            color:
            - 1
            - 1
            - 0
            - 1
          led:
            link: led_link
            color:
            - 0
            - 1
            - 0
            - 1
    movable_objects:
      block_red:
        file: blocks/block_red_middle.urdf
        initial_pos: any
        initial_orn: any
      block_blue:
        file: blocks/block_blue_small.urdf
        initial_pos: any
        initial_orn: any
      block_pink:
        file: blocks/block_pink_big.urdf
        initial_pos: any
        initial_orn: any
  name: calvin_scene_D
robot:
  _target_: calvin_env.robot.robot.Robot
  filename: franka_panda/panda_longer_finger.urdf
  base_position: ${scene.robot_base_position}
  base_orientation: ${scene.robot_base_orientation}
  initial_joint_positions: ${scene.robot_initial_joint_positions}
  max_joint_force: 200.0
  gripper_force: 200
  arm_joint_ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  gripper_joint_ids:
  - 9
  - 11
  gripper_joint_limits:
  - 0
  - 0.04
  tcp_link_id: 15
  end_effector_link_id: 7
  gripper_cam_link: 12
  use_nullspace: true
  max_velocity: 2
  use_ik_fast: false
  magic_scaling_factor_pos: 1
  magic_scaling_factor_orn: 1
  use_target_pose: true
  euler_obs: true
tasks:
  _target_: calvin_env.envs.tasks.Tasks
  tasks:
    rotate_red_block_right:
    - rotate_object
    - block_red
    - -60
    rotate_red_block_left:
    - rotate_object
    - block_red
    - 60
    rotate_blue_block_right:
    - rotate_object
    - block_blue
    - -60
    rotate_blue_block_left:
    - rotate_object
    - block_blue
    - 60
    rotate_pink_block_right:
    - rotate_object
    - block_pink
    - -60
    rotate_pink_block_left:
    - rotate_object
    - block_pink
    - 60
    push_red_block_right:
    - push_object
    - block_red
    - 0.1
    - 0
    push_red_block_left:
    - push_object
    - block_red
    - -0.1
    - 0
    push_blue_block_right:
    - push_object
    - block_blue
    - 0.1
    - 0
    push_blue_block_left:
    - push_object
    - block_blue
    - -0.1
    - 0
    push_pink_block_right:
    - push_object
    - block_pink
    - 0.1
    - 0
    push_pink_block_left:
    - push_object
    - block_pink
    - -0.1
    - 0
    move_slider_left:
    - move_door_rel
    - base__slide
    - 0.15
    move_slider_right:
    - move_door_rel
    - base__slide
    - -0.15
    open_drawer:
    - move_door_rel
    - base__drawer
    - 0.12
    close_drawer:
    - move_door_rel
    - base__drawer
    - -0.12
    lift_red_block_table:
    - lift_object
    - block_red
    - 0.05
    - table
    - base_link
    lift_red_block_slider:
    - lift_object
    - block_red
    - 0.03
    - table
    - plank_link
    lift_red_block_drawer:
    - lift_object
    - block_red
    - 0.05
    - table
    - drawer_link
    lift_blue_block_table:
    - lift_object
    - block_blue
    - 0.05
    - table
    - base_link
    lift_blue_block_slider:
    - lift_object
    - block_blue
    - 0.03
    - table
    - plank_link
    lift_blue_block_drawer:
    - lift_object
    - block_blue
    - 0.05
    - table
    - drawer_link
    lift_pink_block_table:
    - lift_object
    - block_pink
    - 0.05
    - table
    - base_link
    lift_pink_block_slider:
    - lift_object
    - block_pink
    - 0.03
    - table
    - plank_link
    lift_pink_block_drawer:
    - lift_object
    - block_pink
    - 0.05
    - table
    - drawer_link
    place_in_slider:
    - place_object
    - table
    - plank_link
    place_in_drawer:
    - place_object
    - table
    - drawer_link
    stack_block:
    - stack_objects
    unstack_block:
    - unstack_objects
    turn_on_lightbulb:
    - toggle_light
    - lightbulb
    - 0
    - 1
    turn_off_lightbulb:
    - toggle_light
    - lightbulb
    - 1
    - 0
    turn_on_led:
    - toggle_light
    - led
    - 0
    - 1
    turn_off_led:
    - toggle_light
    - led
    - 1
    - 0
    push_into_drawer:
    - push_object_into
    - - block_red
      - block_blue
      - block_pink
    - table
    - base_link
    - table
    - drawer_link
recorder:
  record: ${record}
  record_fps: 30.0
  show_fps: false
  enable_tts: true
seed: 0
use_vr: false
data_path: data
save_dir: /home/edward/projects/mdt_policy/recordings
record: false
load_dir: /home/edward/projects/mdt_policy/calvin_recordings
show_gui: false
processes: 1
max_episode_frames: 1
save_body_infos: true
set_static_cam: false
annotation:
  # rotation
  rotate_red_block_right: ["take the red block and rotate it to the right"]
  rotate_red_block_left: ["take the red block and rotate it to the left"]
  rotate_blue_block_right: ["take the blue block and rotate it to the right"]
  rotate_blue_block_left: ["take the blue block and rotate it to the left"]
  rotate_pink_block_right: ["take the pink block and rotate it to the right"]
  rotate_pink_block_left: ["take the pink block and rotate it to the left"]

  # sliding
  push_red_block_right: ["go push the red block right"]
  push_red_block_left: ["go push the red block left"]
  push_blue_block_right: ["go push the blue block right"]
  push_blue_block_left: ["go push the blue block left"]
  push_pink_block_right: ["go push the pink block right"]
  push_pink_block_left: ["go push the pink block left"]

  # open/close
  move_slider_left: [ "push the sliding door to the left side"]
  move_slider_right: [ "push the sliding door to the right side"]
  open_drawer: ["pull the handle to open the drawer"]
  close_drawer: ["push the handle to close the drawer"]

  # lifting
  lift_red_block_table: ["grasp and lift the red block"]
  lift_blue_block_table: ["grasp and lift the blue block"]
  lift_pink_block_table: ["grasp and lift the pink block"]

  lift_red_block_slider: [ "lift the red block from the sliding cabinet"]
  lift_blue_block_slider: [ "lift the blue block from the sliding cabinet"]
  lift_pink_block_slider: [ "lift the pink block from the sliding cabinet"]

  lift_red_block_drawer: ["Take the red block from the drawer"]
  lift_blue_block_drawer: ["Take the blue block from the drawer"]
  lift_pink_block_drawer: ["Take the pink block from the drawer"]

  place_in_slider: [ "store the grasped block in the sliding cabinet"]
  place_in_drawer: [ "store the grasped block in the drawer"]

  push_into_drawer: ["slide the block that it falls into the drawer"]

  stack_block: ["stack the grasped block"]
  unstack_block: ["remove the stacked block"]

  turn_on_lightbulb: ["use the switch to turn on the light bulb"]
  turn_off_lightbulb: ["use the switch to turn off the light bulb"]
  turn_on_led: ["press the button to turn on the led light"]
  turn_off_led: ["press the button to turn off the led light"]

